# image will be published to ghcr.io/<user>/<name>
name: foundation-blue
# description will be included in the image's metadata
description: This is a direct conversion of the original bluebuild recipe.yml file into separate config files and using base-main as the base image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
    - from-file: directory-base.yml
    - from-file: ostree-base.yml
    - from-file: flatpaks-base.yml
    - from-file: signing-module.yml
